version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_VHOST: vhost
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
